In [2]:
import numpy as np
array1 = np.arange(2, 50, 3)
print(array1)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [3]:
import numpy as np
list_1 = []
list_2 = []
for i in range(5):
  x=int(input('Enter the value for list_1 : '))
  list_1.append(x)
for i in range(5):
  x=int(input('Enter the value for list_2 : '))
  list_2.append(x)
array_1 = np.array(list_1)
array_2 = np.array(list_2)
array3 = np.concatenate((array_1, array_2))
print('Array value for concatenated array 3 :',array3)
sort_array = np.sort(array3)
print("\nSorted Array for concatenated arr :",sort_array)

Enter the value for list_1 : 2
Enter the value for list_1 : 4
Enter the value for list_1 : 6
Enter the value for list_1 : 8
Enter the value for list_1 : 10
Enter the value for list_2 : 1
Enter the value for list_2 : 3
Enter the value for list_2 : 5
Enter the value for list_2 : 7
Enter the value for list_2 : 9
Array value for concatenated array 3 : [ 2  4  6  8 10  1  3  5  7  9]

Sorted Array for concatenated arr : [ 1  2  3  4  5  6  7  8  9 10]


In [5]:
import numpy as np
array1 = np.array([[1,3,5],[2,4,6]])
print('Dimensions in Array : ', array1.ndim)
print('Size of Array : ', array1.size)

Dimensions in Array :  2
Size of Array :  6


In [10]:
# newaxis snippet
import numpy as np
array1 = np.arange(10)
print('Shape of Array : ',array1.shape)
row_array1 = array1[np.newaxis, :]
print('Shape of 2D Array in Row Major :',row_array1.shape)
column_array1 = array1[:, np.newaxis]
print('Shape of 2D Array in Column Major :',column_array1.shape)

Shape of Array :  (10,)
Shape of 2D Array in Row Major : (1, 10)
Shape of 2D Array in Column Major : (10, 1)


In [11]:
# expand_dims snippet
import numpy as np
array1 = np.arange(10)
print('Shape of Array : ',array1.shape)
row_array1 = np.expand_dims(array1, axis=0)
print('Shape of 2D Array in Row Major : ',row_array1.shape)
column_array1 = np.expand_dims(array1, axis=1)
print('Shape of 2D Array in Column Major : ',column_array1.shape)

Shape of Array :  (10,)
Shape of 2D Array in Row Major :  (1, 10)
Shape of 2D Array in Column Major :  (10, 1)


In [12]:
import numpy as np
array_1 = np.square([2, 4, 6, 8, 10])
array_2 = np.square([1, 3, 5, 7, 9])
print('Horizontal Append : ', np.hstack((array_1, array_2)))
print('Vertical Append : ', np.vstack((array_1, array_2)))

Horizontal Append :  [  4  16  36  64 100   1   9  25  49  81]
Vertical Append :  [[  4  16  36  64 100]
 [  1   9  25  49  81]]


In [14]:
import numpy as np
array_1 = np.array([1, 2, 3, 4, 5, 6, 7,8,9, 10, 2, 4, 6, 8, 10, 1, 3, 5, 7, 9, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100])
unique, counts = np.unique(array_1, return_counts=True)
array_2 = np.asarray((unique, counts)).T
print(array_2)

[[  1   3]
 [  2   2]
 [  3   2]
 [  4   3]
 [  5   2]
 [  6   2]
 [  7   2]
 [  8   2]
 [  9   3]
 [ 10   2]
 [ 16   1]
 [ 25   1]
 [ 36   1]
 [ 49   1]
 [ 64   1]
 [ 81   1]
 [100   1]]
